//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanMyPham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pruduct_trangdiem
    {
        public int id { get; set; }
        public Nullable<int> id_category { get; set; }
        public string name { get; set; }
        public Nullable<int> price { get; set; }
        public string detail { get; set; }
        public string img { get; set; }
        public string link { get; set; }
        public string meta { get; set; }
        public Nullable<bool> hide { get; set; }
        public Nullable<int> order { get; set; }
        public Nullable<System.DateTime> date_begin { get; set; }
        public Nullable<System.DateTime> date_update { get; set; }
    
        public virtual category category { get; set; }
    }
}
